### ISSUE TITLE
Wrong metada statements

### ISSUE THREAD

**Issue by gsjunior86** [ldspider/ldspider#17]
When crawling, the metadata statements is not being written correctly.
```
_:header8841276191552302104516 <http://www.w3.org/2006/http#link> "<http://creativecommons.org/licenses/by-sa/3.0/>
;rel=\"license\",<http://dbpedia.org/data/New_York.n3>; rel=\"alternate\"; type=\"text/n3\"; title=\"Structured Descriptor Document (N3/Turtle format)\", <http://dbpedia.org/data/New_York.json>; rel=\"alternate\"; type=\"application/json\"; title=\"Structured Descriptor Document (RDF/JSON format)\", <http://dbpedia.org/data/New_York.atom>; rel=\"alternate\";
 type=\"application/atom+xml\"; title=\"OData (Atom+Feed format)\", <http://dbpedia.org/data/New_York.jsod>; rel=\"alternate\"; type=\"application/odata+json\"; title=\"OData (JSON format)\", <http://dbpedia.org/page/New_York>; rel=\"alternate\"; type=\"text/html\"; title=\"XHTML+RDFa\",
 <http://dbpedia.org/resource/New_York>; rel=\"http://xmlns.com/foaf/0.1/primaryTopic\", <http://dbpedia.org/resource/New_York>; rev=\"describedby\", <http://dbpedia.mementodepot.org/timegate/http://dbpedia.org/data/New_York.xml>; rel=\"timegate\"" <http://dbpedia.org/data/New_York.xml> .
```
The escape character is being printed together.

**Comment by kaefer3000** [comment]
What is the result that should be seen instead?

**Comment by gsjunior86** [comment]
@kaefer3000 
this will produce Sparql Compiler error when try to insert data.

It would be nice if each metadata is stored in a triple statement.

**Comment by kaefer3000** [comment]
The quad appears to me as valid RDF, hence you may want to have a look at your SPARQL software. FWIW, the headers are in the way they appear in the HTTP message. In the HTTP RFC, different cases what multiple headers with the same key mean are discussed, hence we would like to keep the headers as they are on this level.

**Comment by gsjunior86** [comment]
I tried to load the output file in a Jena Model and insert it in Virtuoso and Fuseki. Virtuoso complain about the '\\' char, while in Jena i cannot load it as quads, the model is empty after loading it.

**Comment by kaefer3000** [comment]
As I said, the data to me looks like valid [N-Quads](https://www.w3.org/TR/n-quads/). The backslashes are necessary to escape the quotation marks. [librdf](http://librdf.org/)'s rapper and [Blazegraph](https://blazegraph.github.io/) parse the data without problems. Hence, I don't think this is a bug of ldspider.
