### ISSUE TITLE
mvn clean package fails

### ISSUE THREAD

**Issue by berezovskyi** [ldspider/ldspider#3]
```
[ERROR] Failed to execute goal on project ldspider: Could not resolve dependencies for project com.ontologycentral:ldspider:jar:1.3: Could not find artifact org.semanticweb.yars:nxparser:jar:1.2.5 in ldspider-repo (https://ldspider.googlecode.com/svn/repository) -> [Help 1]
```

From https://github.com/ldspider/ldspider/commit/1742730a26a010069707648aa2a417891418ab4a

**Comment by berezovskyi** [comment]
apparently, no versions of `org.semanticweb.yars:nxparser` under 2.2 were pushed to maven central: https://mvnrepository.com/artifact/org.semanticweb.yars/nxparser

**Comment by berezovskyi** [comment]
`org.semanticweb.yars:nxparser` is also not a valid dependency any more, only its poms are published on central.

Using `nxparser-parsers` causes a lot of errors, which means a port of ldspider for new versions of nxparser is needed unless we can find a repository with a pre-built jar for `nxparser:1.2.5`.

**Comment by kaefer3000** [comment]
Hi, a corresponding nxparser version is now on maven central and I updated the ldspider pom accordingly. If you want to see ldspider compile in its current state, you have to turn off the test cases like:
````sh
$ mvn clean package -Dmaven.test.skip=true
````
