### ISSUE TITLE
ctor argument type mismatch in RedirectTest

### ISSUE THREAD

**Issue by berezovskyi** [ldspider/ldspider#7]
> [ERROR] /Users/andrew/code/ldspider/src/test/java/com/ontologycentral/ldspider/queue/RedirectTest.java:[17,34] constructor BreadthFirstQueue in class com.ontologycentral.ldspider.queue.BreadthFirstQueue cannot be applied to given types;
  required: org.semanticweb.yars.tld.TldManager,com.ontologycentral.ldspider.queue.Redirects,com.ontologycentral.ldspider.seen.Seen,int,int,int,boolean
  found: com.ontologycentral.ldspider.tld.TldManager,int,int
  reason: actual and formal argument lists differ in length

full log: https://gist.github.com/berezovskyi/538c49f1cb65e37c00d70c6f081a57f7

**Comment by kaefer3000** [comment]
I managed to compile. Can you double-check? Maybe you also want to check the nxparser-2.2 branch where we updated some of the code to a more recent nxparser.

**Comment by kaefer3000** [comment]
and by the way, the test cases are not at the state of the code, so you may want to compile without them (sorry)

**Comment by berezovskyi** [comment]
Yes, I tested and there a lot of similar errors unless I disable the tests. But
